// ================= 首页 ==================== //
export const FETCH_HOME_BANNER = 'FETCH_HOME_BANNER';
export const FETCH_HOME_BANNER_FAIL = 'FETCH_HOME_BANNER_FAIL';
export const FETCH_HOME_BANNER_SUCCESS = 'FETCH_HOME_BANNER_SUCCESS';

export const FETCH_HOME_PLAYLIST = 'FETCH_HOME_PLAYLIST';
export const FETCH_HOME_PLAYLIST_FAIL = 'FETCH_HOME_PLAYLIST_FAIL';
export const FETCH_HOME_PLAYLIST_SUCCESS = 'FETCH_HOME_PLAYLIST_SUCCESS';

export const FETCH_HOME_ALBUM = 'FETCH_HOME_ALBUM';
export const FETCH_HOME_ALBUM_FAIL = 'FETCH_HOME_ALBUM_FAIL';
export const FETCH_HOME_ALBUM_SUCCESS = 'FETCH_HOME_ALBUM_SUCCESS';

export const FETCH_HOME_NEWSONG = 'FETCH_HOME_NEWSONG';
export const FETCH_HOME_NEWSONG_FAIL = 'FETCH_HOME_NEWSONG_FAIL';
export const FETCH_HOME_NEWSONG_SUCCESS = 'FETCH_HOME_NEWSONG_SUCCESS';

export const FETCH_HOME_RANK = 'FETCH_HOME_RANK';
export const FETCH_HOME_RANK_FAIL = 'FETCH_HOME_RANK_FAIL';
export const FETCH_HOME_RANK_SUCCESS = 'FETCH_HOME_RANK_SUCCESS';

// ================= 歌单/专辑 列表 ==================== //
export const FETCH_LIST_PLSYLIST = 'FETCH_LIST_PLSYLIST';
export const FETCH_LIST_PLSYLIST_FAIL = 'FETCH_LIST_PLSYLIST_FAIL';
export const FETCH_LIST_PLSYLIST_SUCCESS = 'FETCH_LIST_PLSYLIST_SUCCESS';

export const FETCH_LIST_ALBUM = 'FETCH_LIST_ALBUM';
export const FETCH_LIST_ALBUM_FAIL = 'FETCH_LIST_ALBUM_FAIL';
export const FETCH_LIST_ALBUM_SUCCESS = 'FETCH_LIST_ALBUM_SUCCESS';

// ================= 歌单/专辑 详情 ==================== //
export const FETCH_DETAIL_PLSYLIST = 'FETCH_DETAIL_PLSYLIST';
export const FETCH_DETAIL_PLSYLIST_FAIL = 'FETCH_DETAIL_PLSYLIST_FAIL';
export const FETCH_DETAIL_PLSYLIST_SUCCESS = 'FETCH_DETAIL_PLSYLIST_SUCCESS';

export const FETCH_DETAIL_ALBUM = 'FETCH_DETAIL_ALBUM';
export const FETCH_DETAIL_ALBUM_FAIL = 'FETCH_DETAIL_ALBUM_FAIL';
export const FETCH_DETAIL_ALBUM_SUCCESS = 'FETCH_DETAIL_ALBUM_SUCCESS';



// ================= 公用评论 ==================== //
export const FETCH_COMMON_COMMENT = 'FETCH_COMMON_COMMENT';
export const FETCH_COMMON_COMMENT_FAIL = 'FETCH_COMMON_COMMENT_FAIL';
export const FETCH_COMMON_COMMENT_SUCCESS = 'FETCH_COMMON_COMMENT_SUCCESS';